# Generated by Django 6.0.5 on 2026-05-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_beds_room_has_air_conditioning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('citizenship', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('is_main_guest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='main.booking')),
            ],
        ),
    ]
