# Generated by Django 6.0.5 on 2026-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='is_main_guest',
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
