# Generated by Django 6.0.5 on 2026-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_guest_is_main_guest_alter_guest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('queen (1 big bed for 1 person)', 'Queen (1 big bed for 1 person)'), ('king (bed for 4 people)', 'King (bed for 4 people)')], default='single', max_length=50),
        ),
    ]
